import os

BASE_DATA_PATH     = "/cfs/earth/scratch/vollmflo/BA/data"

# Per-phase image directories for patients whose images live in a flat
# directory. Resolution is case-insensitive at runtime.
PATIENT_IMAGE_DIRS = {
    "P1": os.path.join(BASE_DATA_PATH, "old", "P1", "Pos_neg 12241515", "images", "Train"),
    "P2": os.path.join(BASE_DATA_PATH, "new", "P2", "images", "Train"),
    "P3": os.path.join(BASE_DATA_PATH, "new", "P3", "images", "Train"),
    "P4": os.path.join(BASE_DATA_PATH, "new", "P4", "images", "Train"),
    "P5": os.path.join(BASE_DATA_PATH, "new", "P5", "images", "Train"),
    "P6": os.path.join(BASE_DATA_PATH, "new", "P6", "images", "Train"),
    "P7": os.path.join(BASE_DATA_PATH, "new", "P7", "images", "Train"),
    "P8": os.path.join(BASE_DATA_PATH, "new", "P8", "images", "Train"),
    "P9": os.path.join(BASE_DATA_PATH, "new", "P9",   "images", "Train"),
    "P10": os.path.join(BASE_DATA_PATH, "new", "P10", "images", "Train"),
    "P11": os.path.join(BASE_DATA_PATH, "new", "P11", "images", "Train"),
    "P12": os.path.join(BASE_DATA_PATH, "new", "P12", "images", "Train"),
    "P13": os.path.join(BASE_DATA_PATH, "new", "P13", "images", "Train"),
    "P14": os.path.join(BASE_DATA_PATH, "new", "P14", "images", "Train"),
    "P15": os.path.join(BASE_DATA_PATH, "new", "P15", "images", "Train"),
    "P16": os.path.join(BASE_DATA_PATH, "new", "P16", "images", "Train"),
    "P17": os.path.join(BASE_DATA_PATH, "new", "P17", "images", "Train"),
    "P18": os.path.join(BASE_DATA_PATH, "new", "P18", "images", "Train"),
    "P19": os.path.join(BASE_DATA_PATH, "new", "P19", "images", "Train"),
    "P20": os.path.join(BASE_DATA_PATH, "new", "P20", "images", "Train"),
    "P21": os.path.join(BASE_DATA_PATH, "new", "P21", "images", "Train"),
    "P22": os.path.join(BASE_DATA_PATH, "new", "P22", "images", "Train"),
    "P23": os.path.join(BASE_DATA_PATH, "new", "P23", "images", "Train"),
    "P24": os.path.join(BASE_DATA_PATH, "new", "P24", "images", "Train"),
    "P25": os.path.join(BASE_DATA_PATH, "new", "P25", "images", "Train"),
    "P26": os.path.join(BASE_DATA_PATH, "new", "P26", "images", "Train"),
    "P27": os.path.join(BASE_DATA_PATH, "new", "P27", "images", "Train"),
    "P28": os.path.join(BASE_DATA_PATH, "new", "P28", "images", "Train"),
    "P29": os.path.join(BASE_DATA_PATH, "new", "P29", "images", "Train"),
    "P30": os.path.join(BASE_DATA_PATH, "new", "P30", "images", "Train"),
    "P31": os.path.join(BASE_DATA_PATH, "new", "P31", "images", "Train"),
    "P32": os.path.join(BASE_DATA_PATH, "new", "P32", "images", "Train"),
    "P33": os.path.join(BASE_DATA_PATH, "new", "P33", "images", "Train"),
    "P34": os.path.join(BASE_DATA_PATH, "new", "P34", "images", "Train"),
    "P35": os.path.join(BASE_DATA_PATH, "new", "P35", "images", "Train"),
    "P36": os.path.join(BASE_DATA_PATH, "new", "P36", "images", "Train"),
    "P37": os.path.join(BASE_DATA_PATH, "new", "P37", "images", "Train"),
    "P38": os.path.join(BASE_DATA_PATH, "new", "P38", "images", "Train"),
    "P39": os.path.join(BASE_DATA_PATH, "new", "P39", "images", "Train"),
    "P40": os.path.join(BASE_DATA_PATH, "new", "P40", "images", "Train"),
    "P41": os.path.join(BASE_DATA_PATH, "new", "P41", "images", "Train"),
    "P42": os.path.join(BASE_DATA_PATH, "new", "P42", "images", "Train"),
    "P43": os.path.join(BASE_DATA_PATH, "new", "P43", "images", "Train"),
    "P44": os.path.join(BASE_DATA_PATH, "new", "P44", "images", "Train"),
    "P45": os.path.join(BASE_DATA_PATH, "new", "P45", "images", "Train"),
    "P46": os.path.join(BASE_DATA_PATH, "new", "P46", "images", "Train"),
    "P47": os.path.join(BASE_DATA_PATH, "new", "P47", "images", "Train"),
    "P48": os.path.join(BASE_DATA_PATH, "new", "P48", "images", "Train"),
    "P49": os.path.join(BASE_DATA_PATH, "new", "P49", "images", "Train"),
    "P50": os.path.join(BASE_DATA_PATH, "new", "P50", "images", "Train"),
    "P51": os.path.join(BASE_DATA_PATH, "new", "P51", "images", "Train"),
    "P52": os.path.join(BASE_DATA_PATH, "new", "P52", "images", "Train"),
    "P53": os.path.join(BASE_DATA_PATH, "new", "P53", "images", "Train"),
}


# FP-negative Excel files per patient. Each Excel contains filenames of tiles
# that the model incorrectly detected (confirmed false positives). They are
# resolved against the patient's image index at runtime and added to train-only
# splits as empty-label negatives.
PATIENT_FP_EXCELS = {
    "P2":  os.path.join(BASE_DATA_PATH, "old",  "P2",  "Task 6_1224151_negative.xlsx"),
    "P9":  os.path.join(BASE_DATA_PATH, "new",  "P9",  "Task39_V2.xlsx"),
    "P10": os.path.join(BASE_DATA_PATH, "new",  "P10", "Task26_V2.xlsx"),
    "P11": os.path.join(BASE_DATA_PATH, "new",  "P11", "Task27_V2.xlsx"),
    "P12": os.path.join(BASE_DATA_PATH, "new",  "P12", "Task21_V2.xlsx"),
    "P13": os.path.join(BASE_DATA_PATH, "new",  "P13", "Task24_V2.xlsx"),
    "P14": os.path.join(BASE_DATA_PATH, "new",  "P14", "Task25_V2.xlsx"),
    "P15": os.path.join(BASE_DATA_PATH, "new",  "P15", "Task23_V2.xlsx"),
    "P16": os.path.join(BASE_DATA_PATH, "new", "P16", "Task19_V2.xlsx"),
    "P17": os.path.join(BASE_DATA_PATH, "new", "P17", "Task20_V2.xlsx"),
    "P18": os.path.join(BASE_DATA_PATH, "new", "P18", "Task22_V2.xlsx"),
    "P19": os.path.join(BASE_DATA_PATH, "new", "P19", "Task40_V2.xlsx"),
    "P20": os.path.join(BASE_DATA_PATH, "new", "P20", "Task41_V2.xlsx"),
    "P21": os.path.join(BASE_DATA_PATH, "new", "P21", "Task42_V2.xlsx"),
    "P22": os.path.join(BASE_DATA_PATH, "new", "P22", "Task43_V2.xlsx"),
    "P23": os.path.join(BASE_DATA_PATH, "new", "P23", "Task44_V2.xlsx"),
    "P24": os.path.join(BASE_DATA_PATH, "new", "P24", "Task45_V2.xlsx"),
    "P25": os.path.join(BASE_DATA_PATH, "new", "P25", "Task46_V2.xlsx"),
    "P26": os.path.join(BASE_DATA_PATH, "new", "P26", "Task47_V2.xlsx"),
    "P27": os.path.join(BASE_DATA_PATH, "new", "P27", "Task48_V2.xlsx"),
    "P28": os.path.join(BASE_DATA_PATH, "new", "P28", "Task49_V2.xlsx"),
    "P29": os.path.join(BASE_DATA_PATH, "new", "P29", "Task50_V2.xlsx"),
    "P30": os.path.join(BASE_DATA_PATH, "new", "P30", "Task51_V2.xlsx"),
    "P31": os.path.join(BASE_DATA_PATH, "new", "P31", "Tas52_V2.xlsx"),    # typo in source filename
    "P32": os.path.join(BASE_DATA_PATH, "new", "P32", "Task53_V2.xlsx"),
    "P33": os.path.join(BASE_DATA_PATH, "new", "P33", "Task54_V2.xlsx"),
    "P34": os.path.join(BASE_DATA_PATH, "new", "P34", "Task55_V2.xlsx"),
    "P35": os.path.join(BASE_DATA_PATH, "new", "P35", "Task56_V2.xlsx"),
    "P36": os.path.join(BASE_DATA_PATH, "new", "P36", "Task57_V2.xlsx"),
    "P37": os.path.join(BASE_DATA_PATH, "new", "P37", "Task58_V2.xlsx"),
    "P38": os.path.join(BASE_DATA_PATH, "new", "P38", "Task59_V2.xlsx"),
    "P39": os.path.join(BASE_DATA_PATH, "new", "P39", "Task60_V2xlsx.xlsx"),  # typo in source filename
    "P40": os.path.join(BASE_DATA_PATH, "new", "P40", "Task61_V2.xlsx"),
    "P41": os.path.join(BASE_DATA_PATH, "new", "P41", "Task62_V2.xlsx"),
    "P42": os.path.join(BASE_DATA_PATH, "new", "P42", "Task63_V2.xlsx"),
    "P43": os.path.join(BASE_DATA_PATH, "new", "P43", "Task64_V2.xlsx"),
    "P44": os.path.join(BASE_DATA_PATH, "new", "P44", "Task65_V2xlsx.xlsx"),  # typo in source filename
    "P45": os.path.join(BASE_DATA_PATH, "new", "P45", "Task66_V2.xlsx"),
    "P46": os.path.join(BASE_DATA_PATH, "new", "P46", "Task67_V2.xlsx"),
    "P47": os.path.join(BASE_DATA_PATH, "new", "P47", "Task68_V2.xlsx"),
    "P48": os.path.join(BASE_DATA_PATH, "new", "P48", "Task69_V2.xlsx"),
    "P49": os.path.join(BASE_DATA_PATH, "new", "P49", "Task70_V2.xlsx"),
    "P50": os.path.join(BASE_DATA_PATH, "new", "P50", "Task71_V2.xlsx"),
    "P51": os.path.join(BASE_DATA_PATH, "new", "P51", "Task73_V2.xlsx"),
    "P52": os.path.join(BASE_DATA_PATH, "new", "P52", "Task74_V2.xlsx"),
    "P53": os.path.join(BASE_DATA_PATH, "new", "P53", "Task75_V2.xlsx"),
}
