<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>experiment_log</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="experiment_log_files/libs/clipboard/clipboard.min.js"></script>
<script src="experiment_log_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="experiment_log_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="experiment_log_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="experiment_log_files/libs/quarto-html/popper.min.js"></script>
<script src="experiment_log_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="experiment_log_files/libs/quarto-html/anchor.min.js"></script>
<link href="experiment_log_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="experiment_log_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="experiment_log_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="experiment_log_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="experiment_log_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="experiment-log-mast-cell-detection-pipeline" class="level1">
<h1>Experiment Log — Mast Cell Detection Pipeline</h1>
<p>Tracks all training runs, the reasoning behind each, and conclusions drawn. All results tables show <strong>test-set</strong> metrics (held-out split, evaluated with best.pt after training), plus validation metrics where noted. Val metrics during training are shown separately and are not used for model comparison — the test split is the authoritative number.</p>
<hr>
<section id="background-phase-1-p1-dataset-yolo11n-baseline" class="level2">
<h2 class="anchored" data-anchor-id="background-phase-1-p1-dataset-yolo11n-baseline">Background: Phase 1 — P1 Dataset, YOLO11n Baseline</h2>
<p><strong>Scripts:</strong> <code>ba_improved.py</code><br>
<strong>Results dir:</strong> <code>yolo_runs_hpc_final/</code><br>
<strong>Purpose:</strong> Initial proof of concept on the first patient dataset (P1)</p>
<section id="setup" class="level3">
<h3 class="anchored" data-anchor-id="setup">Setup</h3>
<ul>
<li>Model: <code>yolo11n.pt</code> (COCO pretrained, no domain-specific weights)</li>
<li>Data: P1 — <code>Pos_neg 12241515</code> (annotated positive tiles) + <code>Negativ 12241515</code> (negative tiles)</li>
<li>Classes: Atypisch, Normal</li>
<li>Strategy: 5-fold stratified CV, albumentations augmentation (flip, brightness, rotate ±15°)</li>
<li>Epochs: up to 5000, patience=50, batch=32, imgsz=512, cos_lr=True</li>
</ul>
</section>
<section id="validation-results-best-epoch-per-fold-from-results.csv" class="level3">
<h3 class="anchored" data-anchor-id="validation-results-best-epoch-per-fold-from-results.csv">Validation results (best epoch per fold, from results.csv)</h3>
<p><em>Note: No clean held-out test evaluation available for this phase; val metrics shown.</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fold</th>
<th>Best Epoch</th>
<th>mAP50</th>
<th>mAP50-95</th>
<th>Precision</th>
<th>Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>135</td>
<td>0.9521</td>
<td>0.8051</td>
<td>0.8844</td>
<td>0.9198</td>
</tr>
<tr class="even">
<td>2</td>
<td>112</td>
<td>0.7561</td>
<td>0.5830</td>
<td>0.6343</td>
<td>0.7804</td>
</tr>
<tr class="odd">
<td>3</td>
<td>120</td>
<td>0.8931</td>
<td>0.7449</td>
<td>0.7642</td>
<td>0.7371</td>
</tr>
<tr class="even">
<td>4</td>
<td>128</td>
<td>0.7754</td>
<td>0.6367</td>
<td>0.6710</td>
<td>0.7252</td>
</tr>
<tr class="odd">
<td>5</td>
<td>29</td>
<td>0.6212</td>
<td>0.4734</td>
<td>0.8867</td>
<td>0.4321</td>
</tr>
<tr class="even">
<td><strong>mean</strong></td>
<td></td>
<td><strong>0.800</strong></td>
<td><strong>0.649</strong></td>
<td><strong>0.768</strong></td>
<td><strong>0.719</strong></td>
</tr>
<tr class="odd">
<td><strong>std</strong></td>
<td></td>
<td><strong>0.129</strong></td>
<td><strong>0.131</strong></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>Proof of concept succeeds. Fold 1 achieves excellent results (mAP50=0.952), but the 5-fold mean is dragged down by high fold-to-fold variance (std=0.129). Fold 5 converges at epoch 29 with very low recall (0.432), indicating an unlucky data split rather than a model problem. The high variance becomes the central challenge for all subsequent runs.</p>
<hr>
</section>
</section>
<section id="phase-2-p2-dataset-fine-tuning-experiments" class="level2">
<h2 class="anchored" data-anchor-id="phase-2-p2-dataset-fine-tuning-experiments">Phase 2 — P2 Dataset Fine-Tuning Experiments</h2>
<p>All Phase 2 runs use the P2 dataset: <code>1224151atypisch_normal</code> (annotated images, .jpeg format) with confirmed false-positive negatives loaded from <code>Task 6_1224151_negative.xlsx</code>. Script: <code>ba_improved_P2.py</code> throughout.</p>
<hr>
<section id="run-p2-a-yolo11n-baseline-on-p2-base-settings" class="level3">
<h3 class="anchored" data-anchor-id="run-p2-a-yolo11n-baseline-on-p2-base-settings">Run P2-A — YOLO11n Baseline on P2 (base settings)</h3>
<p><strong>SLURM:</strong> <code>Slurm-319399 (train p2 base nano)</code></p>
<section id="setup-1" class="level4">
<h4 class="anchored" data-anchor-id="setup-1">Setup</h4>
<ul>
<li>Base model: <code>yolo11n.pt</code> (COCO pretrained)</li>
<li>FP_NEG_OVERSAMPLE=1, BG_RATIO=0</li>
<li>Default YOLO hyperparameters (no cfg override)</li>
</ul>
</section>
<section id="test-results" class="level4">
<h4 class="anchored" data-anchor-id="test-results">Test results</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fold</th>
<th>mAP50-95</th>
<th>mAP50</th>
<th>Precision</th>
<th>Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.3222</td>
<td>0.4405</td>
<td>0.8935</td>
<td>0.4205</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.7112</td>
<td>0.8572</td>
<td>0.7222</td>
<td>0.8752</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.4801</td>
<td>0.6221</td>
<td>0.5840</td>
<td>0.5939</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.3800</td>
<td>0.5084</td>
<td>0.4774</td>
<td>0.6044</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0.3678</td>
<td>0.4718</td>
<td>0.3802</td>
<td>0.5905</td>
</tr>
<tr class="even">
<td><strong>mean</strong></td>
<td><strong>0.452</strong></td>
<td><strong>0.580</strong></td>
<td><strong>0.612</strong></td>
<td><strong>0.617</strong></td>
</tr>
<tr class="odd">
<td><strong>std</strong></td>
<td><strong>0.156</strong></td>
<td><strong>0.172</strong></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="conclusion-1" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-1">Conclusion</h4>
<p>Extremely high variance (fold 2 reaches mAP50=0.857, fold 1 only 0.441). Training from the generic yolo11n.pt weights on this specialised domain is unstable. Using domain-specific pretrained weights (DL_Modell_FV.pt) should help.</p>
<hr>
</section>
</section>
<section id="run-p2-b-yolo11n-baseline-on-p2-modified-settings" class="level3">
<h3 class="anchored" data-anchor-id="run-p2-b-yolo11n-baseline-on-p2-modified-settings">Run P2-B — YOLO11n Baseline on P2 (modified settings)</h3>
<p><strong>SLURM:</strong> <code>Slurm-319400 (train p2 mod nano)</code></p>
<section id="setup-2" class="level4">
<h4 class="anchored" data-anchor-id="setup-2">Setup</h4>
<ul>
<li>Base model: <code>yolo11n.pt</code></li>
<li>FP_NEG_OVERSAMPLE=1, BG_RATIO=0</li>
<li>Modified training settings (exact changes not tracked)</li>
</ul>
</section>
<section id="test-results-1" class="level4">
<h4 class="anchored" data-anchor-id="test-results-1">Test results</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fold</th>
<th>mAP50-95</th>
<th>mAP50</th>
<th>Precision</th>
<th>Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.3727</td>
<td>0.4985</td>
<td>0.5299</td>
<td>0.5114</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.7112</td>
<td>0.8572</td>
<td>0.7222</td>
<td>0.8752</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.4801</td>
<td>0.6221</td>
<td>0.5840</td>
<td>0.5939</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.4762</td>
<td>0.6219</td>
<td>0.5478</td>
<td>0.7638</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0.3678</td>
<td>0.4718</td>
<td>0.3802</td>
<td>0.5905</td>
</tr>
<tr class="even">
<td><strong>mean</strong></td>
<td><strong>0.482</strong></td>
<td><strong>0.614</strong></td>
<td><strong>0.553</strong></td>
<td><strong>0.667</strong></td>
</tr>
<tr class="odd">
<td><strong>std</strong></td>
<td><strong>0.139</strong></td>
<td><strong>0.155</strong></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="conclusion-2" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-2">Conclusion</h4>
<p>Marginal improvement in recall over P2-A, but variance remains very high. Fold 2 and 3 share identical results with P2-A, suggesting those folds converged to the same solution regardless of the setting modifications. Domain-specific starting weights are needed.</p>
<hr>
</section>
</section>
<section id="run-p2-c-dl_modell_fv-fine-tuning-base-settings" class="level3">
<h3 class="anchored" data-anchor-id="run-p2-c-dl_modell_fv-fine-tuning-base-settings">Run P2-C — DL_Modell_FV Fine-Tuning (base settings)</h3>
<p><strong>SLURM:</strong> <code>Slurm-319401 (train p2 base dl_fv)</code></p>
<section id="setup-3" class="level4">
<h4 class="anchored" data-anchor-id="setup-3">Setup</h4>
<ul>
<li>Base model: <code>DL_Modell_FV.pt</code> (domain-specific pretrained weights)</li>
<li>FP_NEG_OVERSAMPLE=1, BG_RATIO=0</li>
<li>Default hyperparameters (lr0=0.01), no cfg override</li>
</ul>
</section>
<section id="test-results-2" class="level4">
<h4 class="anchored" data-anchor-id="test-results-2">Test results</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fold</th>
<th>mAP50-95</th>
<th>mAP50</th>
<th>Precision</th>
<th>Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.3088</td>
<td>0.4207</td>
<td>0.8706</td>
<td>0.3763</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.3787</td>
<td>0.5089</td>
<td>0.8824</td>
<td>0.3820</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.3697</td>
<td>0.4945</td>
<td>0.8567</td>
<td>0.4180</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.3445</td>
<td>0.4734</td>
<td>0.9014</td>
<td>0.4234</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0.3156</td>
<td>0.4455</td>
<td>0.8896</td>
<td>0.3870</td>
</tr>
<tr class="even">
<td><strong>mean</strong></td>
<td><strong>0.344</strong></td>
<td><strong>0.469</strong></td>
<td><strong>0.880</strong></td>
<td><strong>0.397</strong></td>
</tr>
<tr class="odd">
<td><strong>std</strong></td>
<td><strong>0.031</strong></td>
<td><strong>0.035</strong></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="conclusion-3" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-3">Conclusion</h4>
<p>Using DL_Modell_FV.pt dramatically reduces variance (std=0.031 vs 0.139–0.156 with yolo11n) — the pretrained domain knowledge stabilises training across folds. However, mean mAP50 (0.469) and recall (0.397) are lower than yolo11n runs. The model is high-precision (0.880) but misses too many cells. This pattern is characteristic of a learning rate too high for fine-tuning: the model’s existing knowledge gets partially overwritten, leaving it conservative and biased toward precision over recall.</p>
<hr>
</section>
</section>
<section id="run-p2-d-dl_modell_fv-fine-tuning-modified-settings" class="level3">
<h3 class="anchored" data-anchor-id="run-p2-d-dl_modell_fv-fine-tuning-modified-settings">Run P2-D — DL_Modell_FV Fine-Tuning (modified settings)</h3>
<p><strong>SLURM:</strong> <code>Slurm-319416 (train p2 mod dl_fv)</code></p>
<section id="setup-4" class="level4">
<h4 class="anchored" data-anchor-id="setup-4">Setup</h4>
<ul>
<li>Base model: <code>DL_Modell_FV.pt</code></li>
<li>FP_NEG_OVERSAMPLE=1, BG_RATIO=0</li>
<li>Modified training settings</li>
</ul>
</section>
<section id="test-results-3" class="level4">
<h4 class="anchored" data-anchor-id="test-results-3">Test results</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fold</th>
<th>mAP50-95</th>
<th>mAP50</th>
<th>Precision</th>
<th>Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.3793</td>
<td>0.5050</td>
<td>0.5503</td>
<td>0.5278</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.4945</td>
<td>0.6386</td>
<td>0.5235</td>
<td>0.9569</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.5313</td>
<td>0.7043</td>
<td>0.7227</td>
<td>0.6587</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.4655</td>
<td>0.6240</td>
<td>0.6549</td>
<td>0.7152</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0.3655</td>
<td>0.4777</td>
<td>0.9217</td>
<td>0.4162</td>
</tr>
<tr class="even">
<td><strong>mean</strong></td>
<td><strong>0.447</strong></td>
<td><strong>0.590</strong></td>
<td><strong>0.675</strong></td>
<td><strong>0.655</strong></td>
</tr>
<tr class="odd">
<td><strong>std</strong></td>
<td><strong>0.072</strong></td>
<td><strong>0.090</strong></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="conclusion-4" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-4">Conclusion</h4>
<p>Best result so far on the test set: mean mAP50=0.590, recall=0.655. The modified settings improve recall substantially over P2-C (0.655 vs 0.397) at the cost of some precision. Variance is still moderate (std=0.090). Fold 2 achieves excellent recall (0.957) but fold 5 remains low (0.416), showing the fold-to-fold instability has not been resolved.</p>
<hr>
</section>
</section>
<section id="run-p2-e-dl_modell_fv-yolo-tuner-hyperparameters-failed" class="level3">
<h3 class="anchored" data-anchor-id="run-p2-e-dl_modell_fv-yolo-tuner-hyperparameters-failed">Run P2-E — DL_Modell_FV + YOLO Tuner Hyperparameters (FAILED)</h3>
<p><strong>SLURM:</strong> <code>Slurm-319536 (train p2 base dl_fv hyperpara)</code></p>
<section id="setup-5" class="level4">
<h4 class="anchored" data-anchor-id="setup-5">Setup</h4>
<ul>
<li>Base model: <code>DL_Modell_FV.pt</code></li>
<li>FP_NEG_OVERSAMPLE=1, BG_RATIO=0</li>
<li>Hyperparameter config from YOLO built-in tuner (<code>cfg=CFG_PATH</code> → <code>best_hyperparameters.yaml</code>)</li>
<li>Tuner was run for 300 epochs × 100 iterations on P2 data (Slurm-269569)</li>
</ul>
</section>
<section id="test-results-4" class="level4">
<h4 class="anchored" data-anchor-id="test-results-4">Test results</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fold</th>
<th>mAP50-95</th>
<th>mAP50</th>
<th>Precision</th>
<th>Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.3292</td>
<td>0.4508</td>
<td>0.9033</td>
<td>0.4005</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.3205</td>
<td>0.4377</td>
<td>0.8816</td>
<td>0.4023</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.3215</td>
<td>0.4535</td>
<td>0.8962</td>
<td>0.4242</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.3308</td>
<td>0.4556</td>
<td>0.9092</td>
<td>0.4124</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0.3243</td>
<td>0.4429</td>
<td>0.8856</td>
<td>0.4269</td>
</tr>
<tr class="even">
<td><strong>mean</strong></td>
<td><strong>0.325</strong></td>
<td><strong>0.448</strong></td>
<td><strong>0.895</strong></td>
<td><strong>0.413</strong></td>
</tr>
<tr class="odd">
<td><strong>std</strong></td>
<td><strong>0.005</strong></td>
<td><strong>0.007</strong></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Training collapsed in 3–6 epochs across all folds. The validation <code>cls_loss</code> reached 5.8+ (normal range: 0.5–1.5), indicating catastrophic forgetting of the pretrained weights.</p>
</section>
<section id="conclusion-5" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-5">Conclusion</h4>
<p><strong>Total failure.</strong> YOLO’s built-in tuner optimises hyperparameters for training from scratch. When those hyperparameters (particularly <code>lr0=0.01</code>) are applied to fine-tuning from a pretrained checkpoint, they overwrite learned features before any adaptation can occur. The near-zero variance (std=0.005) is not stability — it is all folds collapsing to the same degenerate solution. <strong>The <code>cfg=CFG_PATH</code> argument must never be used in fine-tuning runs.</strong></p>
<hr>
</section>
</section>
<section id="run-p2-f-dl_modell_fv-modified-hyperparameters-tuner-config" class="level3">
<h3 class="anchored" data-anchor-id="run-p2-f-dl_modell_fv-modified-hyperparameters-tuner-config">Run P2-F — DL_Modell_FV + Modified Hyperparameters + Tuner Config</h3>
<p><strong>SLURM:</strong> <code>Slurm-319538 (train p2 mod dl_fv hyperpara)</code></p>
<section id="setup-6" class="level4">
<h4 class="anchored" data-anchor-id="setup-6">Setup</h4>
<ul>
<li>Base model: <code>DL_Modell_FV.pt</code></li>
<li>Modified settings combined with hyperparameter cfg</li>
</ul>
</section>
<section id="test-results-5" class="level4">
<h4 class="anchored" data-anchor-id="test-results-5">Test results</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fold</th>
<th>mAP50-95</th>
<th>mAP50</th>
<th>Precision</th>
<th>Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.3552</td>
<td>0.4758</td>
<td>0.3876</td>
<td>0.5770</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.3465</td>
<td>0.4573</td>
<td>0.3599</td>
<td>0.6335</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.3635</td>
<td>0.4879</td>
<td>0.8916</td>
<td>0.4153</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.4582</td>
<td>0.6014</td>
<td>0.5747</td>
<td>0.7264</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0.4032</td>
<td>0.5181</td>
<td>0.5621</td>
<td>0.5013</td>
</tr>
<tr class="even">
<td><strong>mean</strong></td>
<td><strong>0.385</strong></td>
<td><strong>0.508</strong></td>
<td><strong>0.555</strong></td>
<td><strong>0.571</strong></td>
</tr>
<tr class="odd">
<td><strong>std</strong></td>
<td><strong>0.046</strong></td>
<td><strong>0.057</strong></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="conclusion-6" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-6">Conclusion</h4>
<p>Slightly better than the failed P2-E, but worse than P2-D across all metrics. The combination of modified settings with the tuner config does not add benefit over modified settings alone (P2-D: mAP50=0.590 vs P2-F: mAP50=0.508). Confirmed: tuner hyperparameters are counterproductive for fine-tuning.</p>
<hr>
</section>
</section>
<section id="run-p2-g-dl_modell_fv-background-image-sampling-bg_ratio2" class="level3">
<h3 class="anchored" data-anchor-id="run-p2-g-dl_modell_fv-background-image-sampling-bg_ratio2">Run P2-G — DL_Modell_FV + Background Image Sampling (BG_RATIO=2)</h3>
<p><strong>SLURM:</strong> <code>Slurm-319934</code><br>
<strong>Results dir:</strong> <code>yolo_runs_hpc_base_final_dl_fv_bg_ratio_2/</code></p>
<section id="motivation" class="level4">
<h4 class="anchored" data-anchor-id="motivation">Motivation</h4>
<p>To reduce false positives, unlabeled slide tiles (images with no mast cells and no label file) were added to training as confirmed background images. Hypothesis: the model would learn to suppress detections on dense slide background texture.</p>
</section>
<section id="setup-7" class="level4">
<h4 class="anchored" data-anchor-id="setup-7">Setup</h4>
<ul>
<li>Base model: <code>DL_Modell_FV.pt</code></li>
<li>FP_NEG_OVERSAMPLE=1, <strong>BG_RATIO=2</strong> (2 unlabeled background tiles per annotated image)</li>
<li>No cfg override</li>
</ul>
</section>
<section id="test-results-6" class="level4">
<h4 class="anchored" data-anchor-id="test-results-6">Test results</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fold</th>
<th>mAP50-95</th>
<th>mAP50</th>
<th>Precision</th>
<th>Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.3537</td>
<td>0.4683</td>
<td>0.9201</td>
<td>0.4178</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.4317</td>
<td>0.5649</td>
<td>0.4949</td>
<td>0.5617</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.3502</td>
<td>0.4814</td>
<td>0.8883</td>
<td>0.4215</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.3350</td>
<td>0.4576</td>
<td>0.8872</td>
<td>0.4406</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0.5118</td>
<td>0.6799</td>
<td>0.7364</td>
<td>0.5795</td>
</tr>
<tr class="even">
<td><strong>mean</strong></td>
<td><strong>0.396</strong></td>
<td><strong>0.530</strong></td>
<td><strong>0.785</strong></td>
<td><strong>0.484</strong></td>
</tr>
<tr class="odd">
<td><strong>std</strong></td>
<td><strong>0.075</strong></td>
<td><strong>0.090</strong></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Validation training curves showed folds 1, 2, 5 reaching peak mAP50 ~0.945, but folds 3 and 4 peaked at epochs 7 and 43 respectively and never improved (training ran to patience limit).</p>
</section>
<section id="conclusion-7" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-7">Conclusion</h4>
<p>Mixed outcome. Test set precision improved (0.785 vs 0.675 in P2-D), but recall dropped (0.484 vs 0.655) and mean mAP50 is lower (0.530 vs 0.590). The validation curves reveal the root cause: folds 3 and 4 are collapsing immediately after the warmup phase (epoch 7), which is a <strong>learning rate signature</strong> — with <code>lr0=0.01</code> and a domain-pretrained model, the model overshoots its optimal weights in the first few post-warmup steps. BG_RATIO=2 amplifies this instability in unlucky fold splits by diluting the annotated signal. The learning rate, not the data ratio, is the primary bottleneck.</p>
<hr>
</section>
</section>
<section id="run-p2-h-lower-lr-backbone-freeze-no-background-planned" class="level3">
<h3 class="anchored" data-anchor-id="run-p2-h-lower-lr-backbone-freeze-no-background-planned">Run P2-H — Lower LR + Backbone Freeze, No Background (planned)</h3>
<p><strong>SLURM:</strong> next submission<br>
<strong>Status:</strong> pending</p>
<section id="motivation-1" class="level4">
<h4 class="anchored" data-anchor-id="motivation-1">Motivation</h4>
<p>Root cause analysis across all P2 runs points to <code>lr0=0.01</code> (YOLO default, calibrated for training from scratch) being too high when fine-tuning from <code>DL_Modell_FV.pt</code>. A 10× reduction (<code>lr0=0.001</code>) keeps the pretrained feature representations intact while only the detection heads adapt significantly. Freezing the backbone (first 10 layers) additionally prevents the feature extractor from being overwritten during the early aggressive phase of training.</p>
<p>BG_RATIO is set to 0 in this run to isolate the effect of the LR and freeze changes. If the folds become stable, backgrounds can be reintroduced at ratio 1 in a subsequent run.</p>
</section>
<section id="changes-from-p2-g" class="level4">
<h4 class="anchored" data-anchor-id="changes-from-p2-g">Changes from P2-G</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>P2-G</th>
<th>P2-H</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>lr0</code></td>
<td>0.01 (default)</td>
<td><strong>0.001</strong></td>
</tr>
<tr class="even">
<td><code>lrf</code></td>
<td>0.01 (default)</td>
<td><strong>0.01</strong> (final lr = 1e-5)</td>
</tr>
<tr class="odd">
<td><code>freeze</code></td>
<td>—</td>
<td><strong>10</strong> (first 10 layers frozen)</td>
</tr>
<tr class="even">
<td><code>BG_RATIO</code></td>
<td>2</td>
<td><strong>0</strong> (removed to isolate effect)</td>
</tr>
<tr class="odd">
<td><code>FP_NEG_OVERSAMPLE</code></td>
<td>1</td>
<td>1 (unchanged)</td>
</tr>
<tr class="even">
<td><code>cfg</code></td>
<td>not used</td>
<td>not used</td>
</tr>
</tbody>
</table>
</section>
<section id="expected-outcome" class="level4">
<h4 class="anchored" data-anchor-id="expected-outcome">Expected outcome</h4>
<p>All 5 folds should converge rather than peak and collapse, bringing std below ~0.06. Mean test mAP50 expected to remain ≥0.59 (matching P2-D) with more consistent recall.</p>
</section>
<section id="results" class="level4">
<h4 class="anchored" data-anchor-id="results">Results</h4>
<p><em>(to be filled in after SLURM job completes)</em></p>
<hr>
</section>
</section>
</section>
<section id="summary-table-test-set-results-all-p2-runs" class="level2">
<h2 class="anchored" data-anchor-id="summary-table-test-set-results-all-p2-runs">Summary Table — Test Set Results (all P2 runs)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 21%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Run</th>
<th>SLURM</th>
<th>Base Model</th>
<th>BG_RATIO</th>
<th>lr0</th>
<th>freeze</th>
<th>mAP50 (mean±std)</th>
<th>Recall (mean)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P2-A</td>
<td>319399</td>
<td>yolo11n</td>
<td>0</td>
<td>0.01</td>
<td>—</td>
<td>0.580 ± 0.172</td>
<td>0.617</td>
</tr>
<tr class="even">
<td>P2-B</td>
<td>319400</td>
<td>yolo11n (mod)</td>
<td>0</td>
<td>0.01</td>
<td>—</td>
<td>0.614 ± 0.155</td>
<td>0.667</td>
</tr>
<tr class="odd">
<td>P2-C</td>
<td>319401</td>
<td>DL_Modell_FV</td>
<td>0</td>
<td>0.01</td>
<td>—</td>
<td>0.469 ± 0.035</td>
<td>0.397</td>
</tr>
<tr class="even">
<td>P2-D</td>
<td>319416</td>
<td>DL_Modell_FV (mod)</td>
<td>0</td>
<td>0.01</td>
<td>—</td>
<td>0.590 ± 0.090</td>
<td>0.655</td>
</tr>
<tr class="odd">
<td>P2-E</td>
<td>319536</td>
<td>DL_Modell_FV + tuner cfg</td>
<td>0</td>
<td>0.01</td>
<td>—</td>
<td>0.448 ± 0.007 ❌</td>
<td>0.413</td>
</tr>
<tr class="even">
<td>P2-F</td>
<td>319538</td>
<td>DL_Modell_FV + mod + tuner cfg</td>
<td>0</td>
<td>0.01</td>
<td>—</td>
<td>0.508 ± 0.057</td>
<td>0.571</td>
</tr>
<tr class="odd">
<td>P2-G</td>
<td>319934</td>
<td>DL_Modell_FV</td>
<td>2</td>
<td>0.01</td>
<td>—</td>
<td>0.530 ± 0.090</td>
<td>0.484</td>
</tr>
<tr class="even">
<td><strong>P2-H</strong></td>
<td>pending</td>
<td>DL_Modell_FV</td>
<td>0</td>
<td><strong>0.001</strong></td>
<td><strong>10</strong></td>
<td><em>pending</em></td>
<td><em>pending</em></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="planned-run-p2-i-reintroduce-background-at-bg_ratio1" class="level2">
<h2 class="anchored" data-anchor-id="planned-run-p2-i-reintroduce-background-at-bg_ratio1">Planned: Run P2-I — Reintroduce Background at BG_RATIO=1</h2>
<p><em>(contingent on P2-H being stable)</em></p>
<p>If P2-H confirms that <code>lr0=0.001</code> + <code>freeze=10</code> eliminates fold-collapse, backgrounds will be reintroduced at 1:1 ratio (one background tile per annotated image) to test whether they add precision benefit without destabilising training.</p>
<p>If test-set precision is still a concern after P2-H, <code>FP_NEG_OVERSAMPLE</code> will be increased from 1 to 2–3. The FP negatives are high-quality hard negatives (the model’s known failure cases) and increasing their weight is a targeted way to reduce false positives without adding random noise.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>